# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 569)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Data/myico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1041, 551))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(366, 20, 301, 521))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(5)
        self.frame_2.setMidLineWidth(5)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 221, 388))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(True)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_25.setFont(font)
        self.label_25.setAutoFillBackground(True)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_45.setFont(font)
        self.label_45.setAutoFillBackground(True)
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_44.setFont(font)
        self.label_44.setAutoFillBackground(True)
        self.label_44.setObjectName("label_44")
        self.verticalLayout.addWidget(self.label_44)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_46.setFont(font)
        self.label_46.setAutoFillBackground(True)
        self.label_46.setObjectName("label_46")
        self.verticalLayout.addWidget(self.label_46)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.combo_pitch_type = QtWidgets.QComboBox(self.layoutWidget)
        self.combo_pitch_type.setObjectName("combo_pitch_type")
        self.combo_pitch_type.addItem("")
        self.combo_pitch_type.addItem("")
        self.verticalLayout_2.addWidget(self.combo_pitch_type)
        self.line_dpw = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_dpw.setFont(font)
        self.line_dpw.setObjectName("line_dpw")
        self.verticalLayout_2.addWidget(self.line_dpw)
        self.line_dc = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_dc.setFont(font)
        self.line_dc.setObjectName("line_dc")
        self.verticalLayout_2.addWidget(self.line_dc)
        self.line_gap = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_gap.setFont(font)
        self.line_gap.setObjectName("line_gap")
        self.verticalLayout_2.addWidget(self.line_gap)
        self.line_fi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_fi.setFont(font)
        self.line_fi.setObjectName("line_fi")
        self.verticalLayout_2.addWidget(self.line_fi)
        self.line_fe = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_fe.setFont(font)
        self.line_fe.setObjectName("line_fe")
        self.verticalLayout_2.addWidget(self.line_fe)
        self.line_dw = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_dw.setFont(font)
        self.line_dw.setObjectName("line_dw")
        self.verticalLayout_2.addWidget(self.line_dw)
        self.line_z0 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_z0.setFont(font)
        self.line_z0.setObjectName("line_z0")
        self.verticalLayout_2.addWidget(self.line_z0)
        self.line_nz = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_nz.setFont(font)
        self.line_nz.setObjectName("line_nz")
        self.verticalLayout_2.addWidget(self.line_nz)
        self.line_z1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_z1.setFont(font)
        self.line_z1.setObjectName("line_z1")
        self.verticalLayout_2.addWidget(self.line_z1)
        self.line_z2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_z2.setFont(font)
        self.line_z2.setObjectName("line_z2")
        self.verticalLayout_2.addWidget(self.line_z2)
        self.line_alpha = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_alpha.setFont(font)
        self.line_alpha.setObjectName("line_alpha")
        self.verticalLayout_2.addWidget(self.line_alpha)
        self.line_ep = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_ep.setFont(font)
        self.line_ep.setObjectName("line_ep")
        self.verticalLayout_2.addWidget(self.line_ep)
        self.line_nu = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_nu.setFont(font)
        self.line_nu.setObjectName("line_nu")
        self.verticalLayout_2.addWidget(self.line_nu)
        self.line_gr = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_gr.setFont(font)
        self.line_gr.setObjectName("line_gr")
        self.verticalLayout_2.addWidget(self.line_gr)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(680, 20, 351, 161))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(5)
        self.frame_3.setMidLineWidth(5)
        self.frame_3.setObjectName("frame_3")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setAutoFillBackground(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(20, 30, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setAutoFillBackground(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(190, 30, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setAutoFillBackground(True)
        self.label_28.setObjectName("label_28")
        self.line_fxy = QtWidgets.QLineEdit(self.frame_3)
        self.line_fxy.setGeometry(QtCore.QRect(110, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.line_fxy.setFont(font)
        self.line_fxy.setText("")
        self.line_fxy.setObjectName("line_fxy")
        self.line_fz = QtWidgets.QLineEdit(self.frame_3)
        self.line_fz.setGeometry(QtCore.QRect(270, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.line_fz.setFont(font)
        self.line_fz.setText("")
        self.line_fz.setObjectName("line_fz")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(160, 30, 31, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setAutoFillBackground(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        self.label_30.setGeometry(QtCore.QRect(320, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setAutoFillBackground(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        self.label_31.setGeometry(QtCore.QRect(20, 60, 91, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setAutoFillBackground(True)
        self.label_31.setObjectName("label_31")
        self.line_mxy = QtWidgets.QLineEdit(self.frame_3)
        self.line_mxy.setGeometry(QtCore.QRect(110, 60, 41, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.line_mxy.setFont(font)
        self.line_mxy.setText("")
        self.line_mxy.setObjectName("line_mxy")
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setGeometry(QtCore.QRect(160, 60, 31, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setAutoFillBackground(True)
        self.label_32.setObjectName("label_32")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(10, 77, 331, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.buttom_ult = QtWidgets.QPushButton(self.frame_3)
        self.buttom_ult.setEnabled(True)
        self.buttom_ult.setGeometry(QtCore.QRect(272, 88, 51, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setUnderline(True)
        self.buttom_ult.setFont(font)
        self.buttom_ult.setObjectName("buttom_ult")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(20, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setAutoFillBackground(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(20, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setAutoFillBackground(True)
        self.label_34.setObjectName("label_34")
        self.result_qmax = QtWidgets.QLineEdit(self.frame_3)
        self.result_qmax.setGeometry(QtCore.QRect(160, 90, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.result_qmax.setFont(font)
        self.result_qmax.setText("")
        self.result_qmax.setObjectName("result_qmax")
        self.result_smax = QtWidgets.QLineEdit(self.frame_3)
        self.result_smax.setGeometry(QtCore.QRect(160, 130, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.result_smax.setFont(font)
        self.result_smax.setText("")
        self.result_smax.setObjectName("result_smax")
        self.label_47 = QtWidgets.QLabel(self.frame_3)
        self.label_47.setGeometry(QtCore.QRect(230, 90, 31, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setAutoFillBackground(True)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame_3)
        self.label_48.setGeometry(QtCore.QRect(230, 130, 31, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setAutoFillBackground(True)
        self.label_48.setObjectName("label_48")
        self.buttom_plot = QtWidgets.QPushButton(self.frame_3)
        self.buttom_plot.setEnabled(True)
        self.buttom_plot.setGeometry(QtCore.QRect(273, 129, 51, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setUnderline(True)
        self.buttom_plot.setFont(font)
        self.buttom_plot.setObjectName("buttom_plot")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(680, 190, 351, 351))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(5)
        self.frame_4.setMidLineWidth(5)
        self.frame_4.setObjectName("frame_4")
        self.label_37 = QtWidgets.QLabel(self.frame_4)
        self.label_37.setGeometry(QtCore.QRect(10, 10, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_37.setFont(font)
        self.label_37.setAutoFillBackground(True)
        self.label_37.setObjectName("label_37")
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setGeometry(QtCore.QRect(30, 54, 261, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_fat_file_dir = QtWidgets.QLineEdit(self.frame_4)
        self.line_fat_file_dir.setGeometry(QtCore.QRect(20, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.line_fat_file_dir.setFont(font)
        self.line_fat_file_dir.setText("")
        self.line_fat_file_dir.setObjectName("line_fat_file_dir")
        self.buttom_read_fat_file = QtWidgets.QPushButton(self.frame_4)
        self.buttom_read_fat_file.setEnabled(True)
        self.buttom_read_fat_file.setGeometry(QtCore.QRect(202, 28, 121, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setUnderline(True)
        self.buttom_read_fat_file.setFont(font)
        self.buttom_read_fat_file.setObjectName("buttom_read_fat_file")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(10, 231, 331, 111))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(4)
        self.frame_5.setMidLineWidth(4)
        self.frame_5.setObjectName("frame_5")
        self.label_52 = QtWidgets.QLabel(self.frame_5)
        self.label_52.setGeometry(QtCore.QRect(9, 80, 41, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setAutoFillBackground(True)
        self.label_52.setObjectName("label_52")
        self.result_l10r_life = QtWidgets.QLineEdit(self.frame_5)
        self.result_l10r_life.setGeometry(QtCore.QRect(85, 50, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.result_l10r_life.setFont(font)
        self.result_l10r_life.setText("")
        self.result_l10r_life.setObjectName("result_l10r_life")
        self.label_55 = QtWidgets.QLabel(self.frame_5)
        self.label_55.setGeometry(QtCore.QRect(195, 81, 61, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setAutoFillBackground(True)
        self.label_55.setObjectName("label_55")
        self.label_54 = QtWidgets.QLabel(self.frame_5)
        self.label_54.setGeometry(QtCore.QRect(47, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setAutoFillBackground(True)
        self.label_54.setObjectName("label_54")
        self.result_life_N = QtWidgets.QLineEdit(self.frame_5)
        self.result_life_N.setGeometry(QtCore.QRect(85, 20, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.result_life_N.setFont(font)
        self.result_life_N.setText("")
        self.result_life_N.setObjectName("result_life_N")
        self.label_65 = QtWidgets.QLabel(self.frame_5)
        self.label_65.setGeometry(QtCore.QRect(163, 20, 25, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setAutoFillBackground(True)
        self.label_65.setObjectName("label_65")
        self.label_53 = QtWidgets.QLabel(self.frame_5)
        self.label_53.setGeometry(QtCore.QRect(194, 51, 61, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setAutoFillBackground(True)
        self.label_53.setObjectName("label_53")
        self.result_l10r_SF = QtWidgets.QLineEdit(self.frame_5)
        self.result_l10r_SF.setGeometry(QtCore.QRect(259, 50, 58, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.result_l10r_SF.setFont(font)
        self.result_l10r_SF.setText("")
        self.result_l10r_SF.setObjectName("result_l10r_SF")
        self.label_67 = QtWidgets.QLabel(self.frame_5)
        self.label_67.setGeometry(QtCore.QRect(163, 80, 25, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setAutoFillBackground(True)
        self.label_67.setObjectName("label_67")
        self.result_l10mr_SF = QtWidgets.QLineEdit(self.frame_5)
        self.result_l10mr_SF.setGeometry(QtCore.QRect(259, 80, 58, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.result_l10mr_SF.setFont(font)
        self.result_l10mr_SF.setText("")
        self.result_l10mr_SF.setObjectName("result_l10mr_SF")
        self.label_66 = QtWidgets.QLabel(self.frame_5)
        self.label_66.setGeometry(QtCore.QRect(163, 50, 25, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setAutoFillBackground(True)
        self.label_66.setObjectName("label_66")
        self.label_50 = QtWidgets.QLabel(self.frame_5)
        self.label_50.setGeometry(QtCore.QRect(48, 50, 31, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setAutoFillBackground(True)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame_5)
        self.label_51.setGeometry(QtCore.QRect(9, 50, 41, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setAutoFillBackground(True)
        self.label_51.setObjectName("label_51")
        self.label_43 = QtWidgets.QLabel(self.frame_5)
        self.label_43.setGeometry(QtCore.QRect(8, 20, 70, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setAutoFillBackground(True)
        self.label_43.setObjectName("label_43")
        self.result_l10mr_life = QtWidgets.QLineEdit(self.frame_5)
        self.result_l10mr_life.setGeometry(QtCore.QRect(85, 80, 71, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.result_l10mr_life.setFont(font)
        self.result_l10mr_life.setText("")
        self.result_l10mr_life.setObjectName("result_l10mr_life")
        self.label_52.raise_()
        self.result_l10r_life.raise_()
        self.label_55.raise_()
        self.label_54.raise_()
        self.result_life_N.raise_()
        self.label_65.raise_()
        self.label_53.raise_()
        self.result_l10r_SF.raise_()
        self.result_l10mr_SF.raise_()
        self.label_66.raise_()
        self.label_50.raise_()
        self.label_51.raise_()
        self.label_43.raise_()
        self.result_l10mr_life.raise_()
        self.label_67.raise_()
        self.line_3 = QtWidgets.QFrame(self.frame_4)
        self.line_3.setGeometry(QtCore.QRect(30, 207, 261, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(10, 80, 331, 131))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(4)
        self.frame_6.setMidLineWidth(4)
        self.frame_6.setObjectName("frame_6")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(10, 55, 191, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(True)
        self.label_14.setObjectName("label_14")
        self.label_38 = QtWidgets.QLabel(self.frame_6)
        self.label_38.setGeometry(QtCore.QRect(20, 84, 201, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_38.setFont(font)
        self.label_38.setAutoFillBackground(True)
        self.label_38.setObjectName("label_38")
        self.buttom_read_FEM_file = QtWidgets.QPushButton(self.frame_6)
        self.buttom_read_FEM_file.setEnabled(True)
        self.buttom_read_FEM_file.setGeometry(QtCore.QRect(200, 102, 121, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setUnderline(True)
        self.buttom_read_FEM_file.setFont(font)
        self.buttom_read_FEM_file.setObjectName("buttom_read_FEM_file")
        self.buttom_fat_FEM = QtWidgets.QPushButton(self.frame_6)
        self.buttom_fat_FEM.setEnabled(True)
        self.buttom_fat_FEM.setGeometry(QtCore.QRect(230, 51, 85, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setUnderline(True)
        self.buttom_fat_FEM.setFont(font)
        self.buttom_fat_FEM.setObjectName("buttom_fat_FEM")
        self.line_FEM_file_dir = QtWidgets.QLineEdit(self.frame_6)
        self.line_FEM_file_dir.setGeometry(QtCore.QRect(20, 104, 151, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.line_FEM_file_dir.setFont(font)
        self.line_FEM_file_dir.setText("")
        self.line_FEM_file_dir.setObjectName("line_FEM_file_dir")
        self.buttom_fat = QtWidgets.QPushButton(self.frame_6)
        self.buttom_fat.setEnabled(True)
        self.buttom_fat.setGeometry(QtCore.QRect(230, 10, 85, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setUnderline(True)
        self.buttom_fat.setFont(font)
        self.buttom_fat.setToolTip("")
        self.buttom_fat.setObjectName("buttom_fat")
        self.line_4 = QtWidgets.QFrame(self.frame_6)
        self.line_4.setGeometry(QtCore.QRect(20, 32, 261, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(17, 94, 151, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(True)
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(140, 222, 60, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(100, 70, 151, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setAutoFillBackground(True)
        self.label_19.setObjectName("label_19")
        self.frame_6.raise_()
        self.label_37.raise_()
        self.line_2.raise_()
        self.line_fat_file_dir.raise_()
        self.buttom_read_fat_file.raise_()
        self.frame_5.raise_()
        self.line_3.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(790, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(790, 185, 131, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(446, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.frame_ = QtWidgets.QFrame(self.frame)
        self.frame_.setGeometry(QtCore.QRect(10, 20, 341, 521))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.frame_.setFont(font)
        self.frame_.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_.setLineWidth(5)
        self.frame_.setMidLineWidth(5)
        self.frame_.setObjectName("frame_")
        self.label_pic = QtWidgets.QLabel(self.frame_)
        self.label_pic.setGeometry(QtCore.QRect(10, 70, 321, 331))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_pic.setFont(font)
        self.label_pic.setText("")
        self.label_pic.setPixmap(QtGui.QPixmap("Data/PB.png"))
        self.label_pic.setObjectName("label_pic")
        self.label_16 = QtWidgets.QLabel(self.frame_)
        self.label_16.setGeometry(QtCore.QRect(10, 420, 271, 91))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_)
        self.label_17.setGeometry(QtCore.QRect(130, 496, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName("label_2")
        self.frame_4.raise_()
        self.frame_.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "金风变桨轴承滚道强度分析软件"))
        self.label_20.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">变桨类型</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">节圆直径</span><span style=\" font-size:11pt; font-style:italic;\">D1</span><span style=\" font-size:11pt;\">/mm</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">滚道沟心距</span><span style=\" font-size:11pt; font-style:italic;\">h2</span><span style=\" font-size:11pt;\">/mm</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">间隙</span><span style=\" font-size:11pt; font-style:italic;\">gap</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">内圈曲率系数</span><span style=\" font-size:11pt; font-style:italic;\">fi</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">外圈曲率系数</span><span style=\" font-size:11pt; font-style:italic;\">fe</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">钢球直径</span><span style=\" font-size:11pt; font-style:italic;\">Dw</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">滚动体数量/列</span><span style=\" font-size:11pt; font-style:italic;\">Z</span><span style=\" font-size:11pt; font-style:italic; vertical-align:sub;\">0</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">滚道列数/</span><span style=\" font-size:11pt; font-style:italic;\">n</span><span style=\" font-size:11pt; font-style:italic; vertical-align:sub;\">z</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">第一列滚动体数量</span><span style=\" font-size:11pt; font-style:italic;\">Z</span><span style=\" font-size:11pt; font-style:italic; vertical-align:sub;\">1</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">第二列滚动体数量</span><span style=\" font-size:11pt; font-style:italic;\">Z</span><span style=\" font-size:11pt; font-style:italic; vertical-align:sub;\">2</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">初始接触角</span><span style=\" font-size:11pt; font-style:italic;\">α</span><span style=\" font-size:11pt;\">/°</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">弹性模量</span><span style=\" font-size:11pt; font-style:italic;\">E</span><span style=\" font-size:11pt; font-style:italic; vertical-align:sub;\">p</span><span style=\" font-size:11pt;\">/MPa</span></p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">泊松比</span><span style=\" font-size:11pt; font-style:italic;\">v</span><span style=\" font-size:11pt; font-style:italic; vertical-align:sub;\">e</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">游隙</span><span style=\" font-size:11pt; font-style:italic;\">Gr</span></p></body></html>"))
        self.combo_pitch_type.setItemText(0, _translate("MainWindow", "内圈变桨"))
        self.combo_pitch_type.setItemText(1, _translate("MainWindow", "外圈变桨"))
        self.line_dpw.setText(_translate("MainWindow", "2650"))
        self.line_dc.setText(_translate("MainWindow", "112"))
        self.line_gap.setText(_translate("MainWindow", "10"))
        self.line_fi.setText(_translate("MainWindow", "0.52"))
        self.line_fe.setText(_translate("MainWindow", "0.52"))
        self.line_dw.setText(_translate("MainWindow", "76.2"))
        self.line_z0.setText(_translate("MainWindow", "92"))
        self.line_nz.setText(_translate("MainWindow", "2"))
        self.line_z1.setText(_translate("MainWindow", "92"))
        self.line_z2.setText(_translate("MainWindow", "92"))
        self.line_alpha.setText(_translate("MainWindow", "45"))
        self.line_ep.setText(_translate("MainWindow", "205000"))
        self.line_nu.setText(_translate("MainWindow", "0.28"))
        self.line_gr.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">载荷输入</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>径向力Fxy</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>轴向力Fz</p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">KN</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">KN</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p>倾覆力矩Mxy</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">KNm</span></p></body></html>"))
        self.buttom_ult.setText(_translate("MainWindow", "计算"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">最大接触力Q</span><span style=\" font-size:11pt; vertical-align:sub;\">max</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">最大接触应力S</span><span style=\" font-size:11pt; vertical-align:sub;\">max</span></p></body></html>"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">KN</span></p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p>MPa</p></body></html>"))
        self.buttom_plot.setText(_translate("MainWindow", "绘图"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">载荷读取</span></p></body></html>"))
        self.buttom_read_fat_file.setText(_translate("MainWindow", "读取载荷文件"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">L</span><span style=\" font-size:11pt; vertical-align:sub;\">10mr</span><span style=\" font-size:11pt;\">:</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">安全系数</span></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">寿命</span></p></body></html>"))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p>Rev</p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">安全系数</span></p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p>Rev</p></body></html>"))
        self.label_66.setText(_translate("MainWindow", "<html><head/><body><p>Rev</p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">寿命</span></p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">L</span><span style=\" font-size:11pt; vertical-align:sub;\">10r </span><span style=\" font-size:11pt;\">:</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">许用寿命N</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">②读取有限元结果计算疲劳</span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">接触力及接触角结果文件读取</span></p></body></html>"))
        self.buttom_read_FEM_file.setText(_translate("MainWindow", "读取结果文件"))
        self.buttom_fat_FEM.setText(_translate("MainWindow", "寿命计算"))
        self.buttom_fat.setText(_translate("MainWindow", "寿命计算"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">①工程算法计算疲劳</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">计算结果</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">计算方法选择及输入</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">滚道极限强度</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">滚道疲劳寿命计算</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">变桨轴承参数输入</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#949494;\">Developers:</span></p><p><span style=\" color:#949494;\">-- Lovely Couple: Tang Jing and Wang Peide</span></p><p><span style=\" color:#949494;\">-- and Peng Haijun</span></p><p><span style=\" color:#949494;\">Version: 1.00</span></p><p><span style=\" font-style:italic; color:#949494;\"><br/></span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#949494;\">Copyright © by GOLDWIND(China).</span></p><p><span style=\" font-style:italic; color:#949494;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">变桨轴承参数示意图</span></p></body></html>"))
